// <auto-generated />
namespace DataAccessLayerr.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_mig_contactadddate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_mig_contactadddate));
        
        string IMigrationMetadata.Id
        {
            get { return "202404271326356_add_mig_contactadddate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
